version: '2'
services:
    utm-app:
        image: utm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://utm-postgresql:5432/utm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    utm-postgresql:
        extends:
            file: postgresql.yml
            service: utm-postgresql
