version: '2'
services:
    utm-postgresql:
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/utm/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=utm
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
